<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'conseats\\backends\\eventpersistenceinterface' => '/Backends/EventPersistenceInterface.php',
                'conseats\\backends\\eventstore' => '/Backends/EventStore.php',
                'conseats\\backends\\exception' => '/Backends/Exception.php',
                'conseats\\backends\\persistenceinterface' => '/Backends/PersistenceInterface.php',
                'conseats\\configuration' => '/Configuration.php',
                'conseats\\configurationinterface' => '/ConfigurationInterface.php',
                'conseats\\domain\\event' => '/Domain/Event.php',
                'conseats\\domain\\exception' => '/Domain/Exception.php',
                'conseats\\domain\\room' => '/Domain/Room.php',
                'conseats\\domain\\seat' => '/Domain/Seat.php',
                'conseats\\factory' => '/Factory.php',
                'conseats\\factoryinterface' => '/FactoryInterface.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd